name: Setup omni-cache
description: Install and run omni-cache as a background sidecar for CI caching
author: Cirrus Labs

branding:
  icon: database
  color: blue

inputs:
  bucket:
    description: 'S3 bucket name for cache storage'
    required: true
  prefix:
    description: 'Prefix for cache objects'
    required: false
    default: ''
  host:
    description: 'Listen address for omni-cache (host:port format)'
    required: false
    default: 'localhost:12321'
  s3-endpoint:
    description: 'S3 endpoint override (e.g., https://s3.example.com)'
    required: false
    default: ''
  version:
    description:
      'omni-cache version to install (e.g., v0.7.0). Defaults to latest.'
    required: false
    default: 'latest'

outputs:
  cache-endpoint:
    description:
      'The HTTP endpoint for the cache (e.g., http://localhost:12321)'
  cache-socket:
    description: 'The Unix socket path for the cache'
  version:
    description: 'The installed omni-cache version'

runs:
  using: node24
  main: dist/index.js
  post: dist/post.js
  post-if: always()
